name: create-eboot/create-lib

on:
  push:
    branches: [ master ]
    paths:
      - 'src/tools/create-eboot/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/tools/create-eboot/**'

jobs:

  build:
    name: create-eboot
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15.3
      uses: actions/setup-go@v2
      with:
        go-version: '1.15.3'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
        
    - name: Build create-eboot windows
      run: |
        cd src/tools/create-eboot
        GOOS=windows go build -ldflags='-X main.TOOL_MODE=SELF' -o create-eboot.exe
        
    - name: Upload create-eboot windows
      uses: actions/upload-artifact@v2
      with:
        name: create-eboot.exe
        path: src/tools/create-eboot/create-eboot.exe

    - name: Build create-eboot linux
      run: |
        cd src/tools/create-eboot
        go build -ldflags='-X main.TOOL_MODE=SELF' -o create-eboot
        
    - name: Upload create-eboot linux
      uses: actions/upload-artifact@v2
      with:
        name: create-eboot
        path: src/tools/create-eboot/create-eboot

    - name: Build create-lib windows
      run: |
        cd src/tools/create-eboot
        GOOS=windows go build -ldflags='-X main.TOOL_MODE=SPRX' -o create-lib.exe
        
    - name: Upload create-lib windows
      uses: actions/upload-artifact@v2
      with:
        name: create-lib.exe
        path: src/tools/create-eboot/create-lib.exe

    - name: Build create-lib linux
      run: |
        cd src/tools/create-eboot
        go build -ldflags='-X main.TOOL_MODE=SPRX' -o create-lib
        
    - name: Upload create-lib linux
      uses: actions/upload-artifact@v2
      with:
        name: create-lib
        path: src/tools/create-eboot/create-lib
